Options (skip=1)
load data
infile 'tmp/cbip238_log_20220630_rec.csv'
append into table "CBIP238_LOG_20220630_REC"
fields terminated by '*'
trailing nullcols 
(START_TIME,COMPLEX_NO,DATA_SYSTEM_CODE,BANK_CODE,VERSION,MS_SYSTEM_CODE,EN_CODE,DATA_LEN,PROTOCOL_TYPE,REQUEST_TYPE,CLIENT_IP,SERIAL_NO,EXT_DATA,UNIQUE_NO, USER_DATA CHAR(1000000) )